# -*- coding: utf-8 -*-
"""CCF394 2023 CLASSIFICAÇAO DE DIGITOS USANDO SVM E MLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-e4do_vi_ym8Og9-qvcpezLqgMgBx08J
"""

import matplotlib.pyplot as plt
# Importa datasets, classificadores e metricas
from sklearn import datasets, svm, metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import accuracy_score
import numpy as np

#carrega dataset de digitos.
digits = datasets.load_digits()

# os digitos são uma matriz de 8x8 .
print(digits.data[0].shape)
img=digits.data[0]
digits.data[0]



# Criar uma figura com 2 linhas e 4 colunas de subplots
fig, axs = plt.subplots(2, 4)

# Percorrer as linhas e colunas de subplots e exibir cada imagem
k=0
for i in range(2):
    for j in range(4):
        img=digits.data[i*4+j]
        img=np.uint8(img)
        img=np.reshape(img,(8, 8))
        
        axs[i, j].set_title(f"Imagem {i*4+j}")
        
        axs[i, j].imshow(img, cmap='gray')
        axs[i, j].axis('off')

plt.show()

# alterando o shape da imagem para ficar na forma de vetor.
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))

# Criando o classificador
#https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
classifier = svm.SVC(gamma=0.001)

# dividindo dados para treinamento 50%...
X_train, X_test, y_train, y_test = train_test_split(
    data, digits.target, test_size=0.5, shuffle=False)

# Treinando
classifier.fit(X_train, y_train)

# Realizando a predição
predicted = classifier.predict(X_test)

cm = confusion_matrix(y_test, predicted, labels=classifier.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm,  display_labels=classifier.classes_)
disp.plot()
plt.show()

print("Precisão da SVM : ",accuracy_score(y_test, predicted)*100)

import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.neural_network import MLPClassifier
import time
import timeit
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt

from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels

from sklearn.metrics import accuracy_score

classifier = MLPClassifier(hidden_layer_sizes=(30,30), max_iter=300,activation = 'relu',solver='adam',random_state=1)

classifier=classifier.fit(X_train, y_train)

#Predicting y for X_val
y_pred = classifier.predict(X_test)
print("Precisão da rede MPL : ",accuracy_score(y_test, y_pred)*100)

cm = confusion_matrix(y_test, y_pred, labels=classifier.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm,  display_labels=classifier.classes_)
disp.plot()
plt.show()